version: "3.7"
services:
  php:
    build:
      dockerfile: ./separate/Dockerfile
      context: ../
    volumes:
    - ./php-fpm/www.conf:/usr/local/etc/conf.d/www.conf:ro
  nginx:
    image: nginx
    links:
      - php
    ports:
    - "8080:80"
    volumes:
      - ./nginx/benchmark-docker-way.conf:/etc/nginx/conf.d/benchmark-docker-way.conf:ro
